{{- if eq .Values.certificate.issuer "ClusterIssuer" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pt-certificate-{{ .Values.exchange }}-{{ .Values.market }}-{{ .Values.environment }}-{{ .Values.botId }}-{{ .Values.certificate.env }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: tls-{{ .Values.exchange }}-{{ .Values.market }}-{{ .Values.environment }}-{{ .Values.botId }}-{{ .Values.certificate.env }}
  issuerRef:
    kind: {{ .Values.certificate.issuer }} 
    {{- if eq .Values.certificate.env "staging" }}
    name: letsencrypt-staging
    {{- else if eq .Values.certificate.env "production" }}
    name: letsencrypt-production
    {{- end }}
  commonName: {{ .Values.ingress.host }}
  dnsNames:
  - {{ .Values.ingress.host }}
{{- end }}  