apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- if eq .Values.certificate.env "staging" }}
    cert-manager.io/issuer: pt-certificate-{{ .Values.environment }}-{{ .Values.botId }}-{{ .Values.certificate.env }}
    {{- else if eq .Values.certificate.env "production" }}
    cert-manager.io/issuer: pt-certificate-{{ .Values.environment }}-{{ .Values.botId }}-{{ .Values.certificate.env }}
    {{- end }}  
    kubernetes.io/ingress.class: nginx
  name: {{ .Values.ingress.name }}-{{ .Values.environment }}-{{ .Values.botId }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app }}
    exchange: {{ .Values.exchange }}
    environment: {{ .Values.environment }}
    botId: {{ .Values.botId | quote }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.service.name }}-{{ .Values.environment }}-{{ .Values.botId }}-service
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: tls-{{ .Values.ingress.name }}-{{ .Values.environment }}-{{ .Values.botId }}-{{ .Values.certificate.env }}-ingress
status:
  loadBalancer:
    ingress: 
    - ip: 127.0.0.1
