apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: pt-certificate-{{ .Values.exchange }}-{{ .Values.market }}-{{ .Values.environment }}-{{ .Values.botId }}-{{ .Values.certificate.env }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class }} 
    {{- if eq .Values.ingress.class "nginx" }}
    nginx.org/redirect-to-https: {{ .Values.ingress.nginx.annotations.redirectHttps | quote }}
    nginx.org/hsts: {{ .Values.ingress.nginx.annotations.hsts | quote }}
    nginx.org/hsts-include-subdomains: {{ .Values.ingress.nginx.annotations.hstsSubdomain | quote }}
    {{- end }}
  {{- if eq .Values.ingress.name "-" }}
  name: {{ .Values.exchange }}-{{ .Values.market }}-{{ .Values.environment }}-{{ .Values.botId }}-ingress
  {{- else }}
  name: {{ .Values.ingress.name }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app }}
    exchange: {{ .Values.exchange }}
    market: {{ .Values.market }}
    environment: {{ .Values.environment }}
    botId: {{ .Values.botId | quote }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            {{- if eq .Values.ingress.name "-" }}
            name: {{ .Values.exchange }}-{{ .Values.market }}-{{ .Values.environment }}-{{ .Values.botId }}-service
            {{- else }}
            name: {{ .Values.service.name }}
            {{- end }}
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: tls-{{ .Values.exchange }}-{{ .Values.market }}-{{ .Values.environment }}-{{ .Values.botId }}-ingress
status:
  loadBalancer:
    ingress: 
    - ip: 127.0.0.1
