apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-{{ .Values.environment }}-{{ .Values.botId }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app }}
    exchange: {{ .Values.exchange }}
    environment: {{ .Values.environment }}
    botId: {{ .Values.botId | quote }}
spec:
  type: ClusterIP
  ports:
  - name: profit-trailer-http
    port: 8081
    targetPort: 8081
  selector:
    app: {{ .Values.app }}
    exchange: {{ .Values.exchange }}
    environment: {{ .Values.environment }}
    botId: {{ .Values.botId | quote }}