apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.label.app }}
    exchange: {{ .Values.exchange }}
    environment: {{ .Values.environment }}
spec:
  type: ClusterIP
  ports:
  - name: profit-trailer-http
    port: 8081
    targetPort: 8081
  selector:
    app: {{ .Values.label.app }}
    exchange: {{ .Values.exchange }}
    environment: {{ .Values.environment }}