apiVersion: v1
kind: Service
metadata:
  {{- if eq .Values.service.name "-" }}
  name: {{ .Values.exchange }}-{{ .Values.market }}-{{ .Values.environment }}-{{ .Values.botId }}-service
  {{- else }}
  name: {{ .Values.service.name }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app }}
    exchange: {{ .Values.exchange }}
    market: {{ .Values.market }}
    environment: {{ .Values.environment }}
    botId: {{ .Values.botId | quote }}
spec:
  type: ClusterIP
  ports:
  - name: profit-trailer-http
    port: 8081
    targetPort: 8081
  selector:
    app: {{ .Values.app }}
    exchange: {{ .Values.exchange }}
    market: {{ .Values.market }}
    environment: {{ .Values.environment }}
    botId: {{ .Values.botId | quote }}