apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: profit-trailer-{{ .Values.environment }}-{{ .Values.botId }}-workload
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: "profit-trailer"
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}
      exchange: {{ .Values.exchange }}
      market: {{ .Values.market }}
      environment: {{ .Values.environment }}
      botId: {{ .Values.botId | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        exchange: {{ .Values.exchange }}
        market: {{ .Values.market }}
        environment: {{ .Values.environment }}
        botId: {{ .Values.botId | quote }}
    spec:
      containers:
      - name: profit-trailer
        image: {{ .Values.containers.image }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }} 
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }} 
        ports:
        - containerPort: 80
          name: pt-port
        volumeMounts:
        - name: data
          mountPath: /app/ProfitTrailer/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: 
        - "ReadWriteOnce"
      storageClassName: {{ .Values.volumeClaim.storageClassName }} 
      resources:
        requests:
          storage: {{ .Values.volumeClaim.requests.storage }}