# Default values for ptchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: profit-trailer
appName: profit-trailer
exchange: binance

certificate:
  env: staging
  email: email@dot.com

service:
  name: profit-trailer

ingress:
  name: profit-trailer
  annotations: {}
  host: profit-trailer.domain.com
    
containers:
  image: lucasconde/profit-trailer:latest
resources: 
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 768Mi

volumeClaim:
  storageClassName: microk8s-hostpath
  requests:
    storage: 5Gi