# Default values for ptchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: profit-trailer
app: profit-trailer
botId: "01"
exchange: binance
environment: test

certificate:
  env: staging
  email: email@dot.com

service:
  name: profit-trailer

ingress:
  name: profit-trailer
  class: nginx
  nginx:
    annotations:
      redirectHttps: true
      hsts: false
      hstsSubdomain: false
    header: {}
  host: profit-trailer.domain.com
    
containers:
  image: lucasconde/profit-trailer:latest
resources: 
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 768Mi

volumeClaim:
  storageClassName: local-path
  requests:
    storage: 5Gi